name: ML CI/CD Pipeline

on:
  push:
    branches: [ "ci_cd", "main" ]   # CI runs on ci_cd, CD runs on main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r 01_cicd_pipeline/requirements.txt

    - name: Run tests (placeholder)
      run: echo "✅ Tests passed"

  train:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r 01_cicd_pipeline/requirements.txt

    - name: Train model
      run: python 01_cicd_pipeline/train.py

    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: artifacts/model.pkl

  deploy:
    runs-on: ubuntu-latest
    needs: train
    if: github.ref == 'refs/heads/main'   # ✅ only run CD on main
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download trained model
      uses: actions/download-artifact@v4
      with:
        name: trained-model
        path: 02_docker_fastapi/

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mlops-model:latest 02_docker_fastapi

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mlops-model:latest