name: ML CI/CD Pipeline

on:
  push:
    branches: [ "ci_cd" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-train-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4   

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r 01_cicd_pipeline/requirements.txt

    - name: Train model
      run: |
        python 01_cicd_pipeline/train.py

    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: artifacts/model.pkl

  deploy:
    runs-on: ubuntu-latest
    needs: build-train-upload 

    steps:
    - name: Download model
      uses: actions/download-artifact@v4
      with:
        name: trained-model
        path: ./model

    - name: Verify model exists
      run: |
        ls -lh ./model
        echo "✅ Model available for deployment!"